### ISSUE TITLE
Issues Following 7495975 feat: automated migration from view.mappings.list to on_attach

### ISSUE THREAD

**Issue by kola-web** [nvim-tree/nvim-tree.lua#2024]
### Description

update to latest version

### Neovim version

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
编译者 brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

mac

### nvim-tree version

74959750f7823d6e069d3948a645f3c7a4c00638

### Minimal config

```lua
any
```

### Steps to reproduce

Update the plugin to reappear

**Comment by TimOleSanmann** [comment]
I faced the same problem this morning. Seems like neovim doesn't recognize the whole Plugin anymore.

**Comment by TimOleSanmann** [comment]
This will help until the bug is fixed:
```
Plug 'nvim-tree/nvim-tree.lua', { 'commit': '9c97e6449b0b0269bd44e1fd4857184dfa57bb4c'}
```

**Comment by dmytrodubinin** [comment]
The same problem

**Comment by 2KAbhishek** [comment]
+1 same issue

**Comment by 1ocate** [comment]
may be It is relection,
I try type 'g?'  for see help but error 
after update have issue.

![image](https://user-images.githubusercontent.com/29521447/221515785-8d1f3778-30ff-4f13-9c3d-bd0dc72fa81b.png)
`E5108: Error executing lua: ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/help.lua:29: attempt to index local 'desc' (a nil value)
stack traceback:
        ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/help.lua:29: in function 'tidy_desc'
        ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/help.lua:69: in function <...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/help.lua:68>
        vim/shared.lua: in function 'tbl_map'
        ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/help.lua:68: in function 'compute_lines'
        ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:66: in function 'draw'
        ...ree.lua/lua/nvim-tree/actions/tree-modifiers/toggles.lua:35: in function <...ree.lua/lua/nvim-tree/actions/tree-modifiers/toggles.lua:33>
`

**Comment by 1ocate** [comment]
> This will help until the bug is fixed:
> 
> ```
> Plug 'nvim-tree/nvim-tree.lua', { 'commit': '9c97e6449b0b0269bd44e1fd4857184dfa57bb4c'}
> ```

It is work for me, that commit is HEAD^

**Comment by alex-courtis** [comment]
> may be It is relection,
> I try type 'g?' for see help but error
> after update have issue.

Fixed. The "no mapping description" case wasn't handled.

Please reply if you have any further issues; are there any messages or errors when starting?

**Comment by 1ocate** [comment]
@alex-courtis For me works ok.
Thank you Great Job.

**Comment by svanharmelen** [comment]
I still have an issue, which seems still the same issue:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/4171547/221565100-ef0f3e1e-dfa7-49c7-98f4-35a27548b09a.png">

**Comment by alex-courtis** [comment]
> I still have an issue, which seems still the same issue:

Thank you for the details. I'll get right on that in the morning.

**Comment by alex-courtis** [comment]
https://github.com/svanharmelen/dotfiles/blob/master/nvim/lua/plugins/nvim-tree.lua#L9

`nvim_tree_callback` was removed following deprecation ~1 year ago.

As it is still in use it will be restored, although it will take some time to write a backwards compatibility shim.

A proper migration (with notification and mechanism) will be developed afterwards.

**Comment by svanharmelen** [comment]
Ah... Check! So is there an alternative? For the callback that I could/should use?

Then I'll update my config...

**Comment by alex-courtis** [comment]
> Ah... Check! So is there an alternative for the callback that I could/should use?
> 
> Then I'll update my config...

Remove callback and use `action = "dir_up"`

**Comment by svanharmelen** [comment]
Thanks for the pointer, will have a look tomorrow morning.

And thanks for your efforts on this plugin, much appeciated!

**Comment by alex-courtis** [comment]
`nvim_tree_callback` has been restored, `view.mappings.list..cb` should now function as before.

Please visit [wiki: Migrating To on_attach](https://github.com/nvim-tree/nvim-tree.lua/wiki/Migrating-To-on_attach) to generate an `on_attach` for your existing mappings.

**Comment by sirutBuasai** [comment]
Does `: NvimTreeGenerateOnAttach` command require nightly neovim? I'm on stable 0.8 and it doesn't seem to recognize the command.

**Comment by svanharmelen** [comment]
Updated my config, so I'm all good again... 👍🏻

**Comment by przepompownia** [comment]
It seems that inserting
```lua
require('nvim-tree.keymap').default_on_attach(bufnr)
```
on the top of custom `on_attach` body can be enough to restore all default mappings lost after the change. It would be better way instead of generating all mappings assuming that we can rely on it (and having to regenerate them sometimes). What do you think @alex-courtis?

**Comment by alex-courtis** [comment]
> What do you think @alex-courtis?

We'll get back to you...

**Comment by alex-courtis** [comment]
@przepompownia see `:help nvim-tree.api.config.mappings.default_on_attach()`

 [Alternative Default Mappings](https://github.com/nvim-tree/nvim-tree.lua/wiki/Migrating-To-on_attach#alternative-default-mappings)

**Comment by przepompownia** [comment]
Thanks, I see that the method I used previously is [now](https://github.com/nvim-tree/nvim-tree.lua/commit/bbb6d4891009de7dab05ad8fc2d39f272d7a751c) available from `nvim-tree.api` :+1:

**Comment by alex-courtis** [comment]
We have stability.
